### ISSUE TITLE
Make this addon more discoverable

### ISSUE THREAD

**Issue by vintprox** [Erghel/SearXNG-Web-Exstension#1]
I barely could find this useful extension on Firefox Addons page. Had to find it through external search engine.

It needs to leverage more keywords in description, like "searx". "SearXNG" doesn't appear anywhere in the first page of search by keywords "searx", which makes it seem like an oversight. Firefox Addons catalog has a bit unintuitive search mechanism, unfortunately.

> "How come Firefox doesn't come bundled with SearXNG search provider out-of-the-box?"

Now, that's another question, but it should be addressed to Firefox repositories. Let alone their binding to Google-first, of course.

**Comment by vintprox** [comment]
@Erghel I made a some PRs to address this. Please have a look when you can. 🙂

**Comment by Erghel** [comment]
Thank you so much for your attention and interest in this extension. I have carefully studied the suggested changes and am willing to agree that the extension is hard to find, we will definitely fix that. 

Thank you also for your Pull Requests

**Comment by Erghel** [comment]
new addon version is aviable 
https://addons.mozilla.org/en-US/firefox/addon/searxng-search/

**Comment by vintprox** [comment]
> new addon version is aviable https://addons.mozilla.org/en-US/firefox/addon/searxng-search/

Man, this is splendid fast! Wish Firefox Addons website was more clear about how long it takes to update their search index, because adding keywords in the description didn't make much... yet.

**Comment by Erghel** [comment]
Unfortunately, for the extension to become more popular - you need more downloads, then on request "SearX..." will give out this extension. 

I will try to make it easier to find it anyway! 
Thank you for your review
