### ISSUE TITLE
Working suggestions

### ISSUE THREAD

**Issue by vintprox** [Erghel/SearXNG-Web-Exstension#4]
So, it's another UX concern when it comes to metasearch. There actually might be a way to [make suggestions work](https://www.reddit.com/r/firefox/comments/mebig2/how_do_i_get_searx_to_autocomplete_search_results/gsfq8cg/).

And this file has a useful link in it: <https://searx.be/opensearch.xml>.

This one autocompletes the query: `https://searx.be/autocompleter?q={searchTerms}`.

**Comment by Erghel** [comment]
Thanks a lot for this issue.
