### ISSUE TITLE
Option for selecting other instances of Searx(ng)

### ISSUE THREAD

**Issue by derkrasseleo** [Erghel/SearXNG-Web-Exstension#8]
Could you add a simple option where I can put in the link to my searx instance?

**Comment by Erghel** [comment]
Could you explain a little more please?

**Comment by derkrasseleo** [comment]
A textfile for input when I click on the icon in the toolbar: 
![searxbox](https://user-images.githubusercontent.com/16163571/167067590-bb7fb201-1f2c-4f8d-ad19-a45f857b3412.jpg)

**Comment by Erghel** [comment]
This function does not fit the meaning of the extension. The extension is designed to change the search engine from yours to SearXNG and that's it. 
If you want to install your own search engine, you can search for the appropriate tools

**Comment by derkrasseleo** [comment]
> This function does not fit the meaning of the extension. The extension is designed to change the search engine from yours to SearXNG and that's it. If you want to install your own search engine, you can search for the appropriate tools

Sorry, I misspelled,  I meant a text field 😅 
But wouldn't it be fair to change which instance to use? What if the specific instance you chose (serx.be) went offline for example?
Or is there a specific reason why you chose this instance?

**Comment by Erghel** [comment]
Yes, I chose a particular version, guided by this website - https://searx.space/

On it you can find all available SearX(NG) search engine hosts. If you want to get an addon with another SearX search engine - I can make one for you or send you ready-made addons from Firefox Addon. 

To answer your question, what happens if the search engine goes offline - my team and I will deploy it on our server and present it to the community.

**Comment by derkrasseleo** [comment]
Oh, so only you can change the searx instance? Is it not possible to make it user-configurable?

**Comment by ecker00** [comment]
Would be nice to have an option to edit the `manifest.json` file, and point it to a custom Searx instance. Just a way to edit the line `"search_url": "https://searx.be/search?q={searchTerms}",` and `"suggest_url"`, could make this addon fit for any Searx server.

Currently found this by going to `about:debugging` picking out the Internal UUID of this addon and accessing `moz-extension://<UUID HERE>/manifest.json`, but can't edit it, without making my own copy of this addon.

**EDIT:**
Maybe your conclusion is right, I got this working using this add-on instead:
https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/
